
# it is used to log the sql on console.
logging:
#  pattern:
#    level: "%5P ${HOSTNAME}"
#    console:
  file:
    name: target/news.log
  level:
    sql: debug
    '[com.practice.session2]': DEBUG

spring:
  sql:
    like:
      operator: '%'
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  h2:
    console:
      enabled: true
  datasource:
#    url: ${NEWS_DB_URL}
#    user: ${NEWS_DB_USER}
#    password: ${NEWS_DB_PASSWORD}
    url: ${news.db.url}
    user: ${news.db.user}
    password: ${news.db.password}

#  datasource:
#    initialization-mode: always
#    data: classpath:data3.sql
#    schema: classpath:schema3.sql

server:
  port: 9080

spring.profiles.include: dev
